### ISSUE TITLE
Replace end button with 1 question survey

### ISSUE THREAD

**Issue by maxhollingdale-new** [i-dot-ai/caddy-chatbot#116]
Having issues with both survey completion and caddy session being ended at the end of a call.

We want to reduce the onerous task of completing a survey down to a single question.

We also want to have a single end button be linked to the survey, meaning survey completion = end of the caddy session

Make the only survey question about confidence

**Comment by mhgov** [comment]
"How confident did you feel in providing advice on the last call?"

**Comment by mhgov** [comment]
completed by kurtis
